### PR TITLE
refactor: footerItem display

### PR DESCRIPTION
**Pull request by jiyuujin**
|PC|Mobile|
|:---|:---|
|スクリーンショット 2021-09-17 8 29 31|スクリーンショット 2021-09-17 8 29 49|

### CODE REVIEW

**Comment by mightyfrog** [comment]
I don't see button labels on Android. Also, text size might be too small on Chrome.
flutter_01

**Comment by mightyfrog** [comment]
screenshot_2

**Comment by jiyuujin** [comment]
What is displayed is too thick..

**Comment by jiyuujin** [comment]
Confirmed on iPhone Xs Max / Pixel 3a

**Comment by jiyuujin** [comment]
Confirmed on iPhone Xs Max / Pixel 3a

**Comment by mightyfrog** [comment]
Labels are still too small or buttons are too fat?
flutter_01

**Comment by mightyfrog** [comment]
Simple TextButton might be better fit in here. All of them in one or two lines including "Licenses".

**Comment by mightyfrog** [comment]
That was just my two cents but here's my take. What do you think?


flutter_02
wrapping

**Comment by mightyfrog** [comment]
Now text size could be a little smaller, I think.

**Comment by mightyfrog** [comment]
Moving "Contact Us" to the end might be a good idea.

**Comment by mightyfrog** [comment]
https://github.com/FlutterKaigi/confwebsite2021/tree/enhance/footerItem-display-alt

**Comment by mightyfrog** [comment]
https://github.com/FlutterKaigi/confwebsite2021/tree/enhance/footerItem-display-alt

- remove fixed spacing
- use Wrap + TextButton
- change wording (License to Licenses)

**Pull request closed without merging**
