### PR TITLE
refactor: footerItem display

### PR DESCRIPTION
**Pull request by jiyuujin**
https://github.com/FlutterKaigi/confwebsite2021/pull/47 was complicated, so I remade it

Includes:
- remove fixed spacing
- use Wrap + TextButton
- change wording (License to Licenses)

ref: https://github.com/FlutterKaigi/confwebsite2021/pull/47#issuecomment-921994452

### CODE REVIEW

**Comment by mightyfrog** [comment]
> #47 was complicated, so I remade it
> 
> Includes:
> 
> * remove fixed spacing
> * use Wrap + TextButton
> * change wording (License to Licenses)
> 
> ref: [#47 (comment)](https://github.com/FlutterKaigi/confwebsite2021/pull/47#issuecomment-921994452)

Diff says otherwise. ???

**Comment by mightyfrog** [comment]
Pixel 4


flutter_01

**Comment by mightyfrog** [comment]
I created a pull request from my changes. I think adding changes on top of it would be easier.

https://github.com/FlutterKaigi/confwebsite2021/pull/49

**Comment by jiyuujin** [comment]
Need to be adjusted, but closed it

**Pull request closed without merging**
