### PR TITLE
Enhance/footer item display alt

### PR DESCRIPTION
**Pull request by mightyfrog**
Alternative fix to item display

- remove fixed spacing
- use Wrap + TextButton (no fixed sizes)
- change wording (License to Licenses)

### CODE REVIEW

**Comment by mightyfrog** [comment]
Chrome (win)

chrome_win

**Comment by mightyfrog** [comment]
Pixel 4

pixel4

**Comment by mightyfrog** [comment]
Pixel 4 XL

pixel4xl

**Comment by mightyfrog** [comment]
iPhone 12 Pro

iPhone 12 Pro

**Review by jiyuujin — APPROVED** [review]
🙏

**Pull request merged**
